apiVersion: v1
kind: Pod
metadata:
  name: debug-shell-vm0
  namespace: default
spec:
  nodeName: myvm000000
  hostNetwork: true
  hostPID: true
  restartPolicy: Never
  containers:
  - name: debug
    image: nicolaka/netshoot
    command: ["/bin/bash"]
    args: ["-c", "echo 'Debug shell ready on myvm000000'; while true; do sleep 3600; done"]
    securityContext:
      privileged: true
      runAsUser: 0
    volumeMounts:
    - name: host-root
      mountPath: /host
    - name: var-run
      mountPath: /host-var-run
    - name: etc
      mountPath: /host-etc
  volumes:
  - name: host-root
    hostPath:
      path: /
  - name: var-run
    hostPath:
      path: /var/run
  - name: etc
    hostPath:
      path: /etc
  tolerations:
  - operator: Exists
---
apiVersion: v1
kind: Pod
metadata:
  name: debug-shell-vm1
  namespace: default
spec:
  nodeName: myvm000001
  hostNetwork: true
  hostPID: true
  restartPolicy: Never
  containers:
  - name: debug
    image: nicolaka/netshoot
    command: ["/bin/bash"]
    args: ["-c", "echo 'Debug shell ready on myvm000001'; while true; do sleep 3600; done"]
    securityContext:
      privileged: true
      runAsUser: 0
    volumeMounts:
    - name: host-root
      mountPath: /host
    - name: var-run
      mountPath: /host-var-run
    - name: etc
      mountPath: /host-etc
  volumes:
  - name: host-root
    hostPath:
      path: /
  - name: var-run
    hostPath:
      path: /var/run
  - name: etc
    hostPath:
      path: /etc
  tolerations:
  - operator: Exists