// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.1
// source: draProtos/dra.proto

package draProtos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Node_PrepareResources_FullMethodName   = "/dra.Node/PrepareResources"
	Node_UnprepareResources_FullMethodName = "/dra.Node/UnprepareResources"
	Node_ConfigureNetwork_FullMethodName   = "/dra.Node/ConfigureNetwork"
)

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeClient interface {
	PrepareResources(ctx context.Context, in *PrepareResourcesRequest, opts ...grpc.CallOption) (*PrepareResourcesResponse, error)
	UnprepareResources(ctx context.Context, in *UnprepareResourcesRequest, opts ...grpc.CallOption) (*UnprepareResourcesResponse, error)
	ConfigureNetwork(ctx context.Context, in *ConfigureNetworkRequest, opts ...grpc.CallOption) (*ConfigureNetworkResponse, error)
}

type nodeClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeClient(cc grpc.ClientConnInterface) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) PrepareResources(ctx context.Context, in *PrepareResourcesRequest, opts ...grpc.CallOption) (*PrepareResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareResourcesResponse)
	err := c.cc.Invoke(ctx, Node_PrepareResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) UnprepareResources(ctx context.Context, in *UnprepareResourcesRequest, opts ...grpc.CallOption) (*UnprepareResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnprepareResourcesResponse)
	err := c.cc.Invoke(ctx, Node_UnprepareResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) ConfigureNetwork(ctx context.Context, in *ConfigureNetworkRequest, opts ...grpc.CallOption) (*ConfigureNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureNetworkResponse)
	err := c.cc.Invoke(ctx, Node_ConfigureNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServer is the server API for Node service.
// All implementations must embed UnimplementedNodeServer
// for forward compatibility.
type NodeServer interface {
	PrepareResources(context.Context, *PrepareResourcesRequest) (*PrepareResourcesResponse, error)
	UnprepareResources(context.Context, *UnprepareResourcesRequest) (*UnprepareResourcesResponse, error)
	ConfigureNetwork(context.Context, *ConfigureNetworkRequest) (*ConfigureNetworkResponse, error)
	mustEmbedUnimplementedNodeServer()
}

// UnimplementedNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServer struct{}

func (UnimplementedNodeServer) PrepareResources(context.Context, *PrepareResourcesRequest) (*PrepareResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareResources not implemented")
}
func (UnimplementedNodeServer) UnprepareResources(context.Context, *UnprepareResourcesRequest) (*UnprepareResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnprepareResources not implemented")
}
func (UnimplementedNodeServer) ConfigureNetwork(context.Context, *ConfigureNetworkRequest) (*ConfigureNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigureNetwork not implemented")
}
func (UnimplementedNodeServer) mustEmbedUnimplementedNodeServer() {}
func (UnimplementedNodeServer) testEmbeddedByValue()              {}

// UnsafeNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServer will
// result in compilation errors.
type UnsafeNodeServer interface {
	mustEmbedUnimplementedNodeServer()
}

func RegisterNodeServer(s grpc.ServiceRegistrar, srv NodeServer) {
	// If the following call pancis, it indicates UnimplementedNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Node_ServiceDesc, srv)
}

func _Node_PrepareResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).PrepareResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_PrepareResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).PrepareResources(ctx, req.(*PrepareResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_UnprepareResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnprepareResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).UnprepareResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_UnprepareResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).UnprepareResources(ctx, req.(*UnprepareResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_ConfigureNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).ConfigureNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_ConfigureNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).ConfigureNetwork(ctx, req.(*ConfigureNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Node_ServiceDesc is the grpc.ServiceDesc for Node service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Node_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dra.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrepareResources",
			Handler:    _Node_PrepareResources_Handler,
		},
		{
			MethodName: "UnprepareResources",
			Handler:    _Node_UnprepareResources_Handler,
		},
		{
			MethodName: "ConfigureNetwork",
			Handler:    _Node_ConfigureNetwork_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "draProtos/dra.proto",
}
