apiVersion: v1
kind: Pod
metadata:
  name: debug-myvm3000004
spec:
  nodeSelector:
    kubernetes.io/hostname: myvm3000004
  hostNetwork: true
  containers:
  - name: debug
    image: nicolaka/netshoot
    command: ["/bin/bash"]
    args: ["-c", "while true; do sleep 30; done"]
    securityContext:
      privileged: true
  restartPolicy: Never