apiVersion: resource.k8s.io/v1beta2
kind: ResourceClaimTemplate
metadata:
  name: single-nic
spec:
  spec:
    devices:
      requests:
        - name: nic
          exactly:
            count: 1
            allocationMode: ExactCount
            deviceClassName: dra-secondarynic