apiVersion: v1
kind: Pod
metadata:
  name: test-ip-change
  namespace: default
spec:
  containers:
  - name: test-container
    image: nicolaka/netshoot
    command: ["/bin/bash"]
    args: ["-c", "sleep 3600"]
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_ADMIN"]
      privileged: true
  hostNetwork: false
  restartPolicy: Never
  nodeName: myvm000000