// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.1
// source: dra.proto

package draProtos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrepareResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claims        map[string]string      `protobuf:"bytes,1,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // claimUID -> opaque JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareResourcesRequest) Reset() {
	*x = PrepareResourcesRequest{}
	mi := &file_dra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareResourcesRequest) ProtoMessage() {}

func (x *PrepareResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareResourcesRequest.ProtoReflect.Descriptor instead.
func (*PrepareResourcesRequest) Descriptor() ([]byte, []int) {
	return file_dra_proto_rawDescGZIP(), []int{0}
}

func (x *PrepareResourcesRequest) GetClaims() map[string]string {
	if x != nil {
		return x.Claims
	}
	return nil
}

type PrepareResourcesResponse struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	PreparedResources map[string]*PreparedResource `protobuf:"bytes,1,rep,name=preparedResources,proto3" json:"preparedResources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PrepareResourcesResponse) Reset() {
	*x = PrepareResourcesResponse{}
	mi := &file_dra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareResourcesResponse) ProtoMessage() {}

func (x *PrepareResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareResourcesResponse.ProtoReflect.Descriptor instead.
func (*PrepareResourcesResponse) Descriptor() ([]byte, []int) {
	return file_dra_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareResourcesResponse) GetPreparedResources() map[string]*PreparedResource {
	if x != nil {
		return x.PreparedResources
	}
	return nil
}

type PreparedResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CdiDevices    []string               `protobuf:"bytes,1,rep,name=cdiDevices,proto3" json:"cdiDevices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreparedResource) Reset() {
	*x = PreparedResource{}
	mi := &file_dra_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreparedResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreparedResource) ProtoMessage() {}

func (x *PreparedResource) ProtoReflect() protoreflect.Message {
	mi := &file_dra_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreparedResource.ProtoReflect.Descriptor instead.
func (*PreparedResource) Descriptor() ([]byte, []int) {
	return file_dra_proto_rawDescGZIP(), []int{2}
}

func (x *PreparedResource) GetCdiDevices() []string {
	if x != nil {
		return x.CdiDevices
	}
	return nil
}

type UnprepareResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimUIDs     []string               `protobuf:"bytes,1,rep,name=claimUIDs,proto3" json:"claimUIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnprepareResourcesRequest) Reset() {
	*x = UnprepareResourcesRequest{}
	mi := &file_dra_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnprepareResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnprepareResourcesRequest) ProtoMessage() {}

func (x *UnprepareResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dra_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnprepareResourcesRequest.ProtoReflect.Descriptor instead.
func (*UnprepareResourcesRequest) Descriptor() ([]byte, []int) {
	return file_dra_proto_rawDescGZIP(), []int{3}
}

func (x *UnprepareResourcesRequest) GetClaimUIDs() []string {
	if x != nil {
		return x.ClaimUIDs
	}
	return nil
}

type UnprepareResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnprepareResourcesResponse) Reset() {
	*x = UnprepareResourcesResponse{}
	mi := &file_dra_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnprepareResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnprepareResourcesResponse) ProtoMessage() {}

func (x *UnprepareResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dra_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnprepareResourcesResponse.ProtoReflect.Descriptor instead.
func (*UnprepareResourcesResponse) Descriptor() ([]byte, []int) {
	return file_dra_proto_rawDescGZIP(), []int{4}
}

type ConfigureNetworkRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PodNamespace   string                 `protobuf:"bytes,1,opt,name=podNamespace,proto3" json:"podNamespace,omitempty"`
	PodName        string                 `protobuf:"bytes,2,opt,name=podName,proto3" json:"podName,omitempty"`
	ContainerName  string                 `protobuf:"bytes,3,opt,name=containerName,proto3" json:"containerName,omitempty"`
	ContainerPid   int32                  `protobuf:"varint,4,opt,name=containerPid,proto3" json:"containerPid,omitempty"`
	PodUID         string                 `protobuf:"bytes,5,opt,name=podUID,proto3" json:"podUID,omitempty"`
	ResourceClaims []*ResourceClaim       `protobuf:"bytes,6,rep,name=resourceClaims,proto3" json:"resourceClaims,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigureNetworkRequest) Reset() {
	*x = ConfigureNetworkRequest{}
	mi := &file_dra_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureNetworkRequest) ProtoMessage() {}

func (x *ConfigureNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dra_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureNetworkRequest.ProtoReflect.Descriptor instead.
func (*ConfigureNetworkRequest) Descriptor() ([]byte, []int) {
	return file_dra_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigureNetworkRequest) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *ConfigureNetworkRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *ConfigureNetworkRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ConfigureNetworkRequest) GetContainerPid() int32 {
	if x != nil {
		return x.ContainerPid
	}
	return 0
}

func (x *ConfigureNetworkRequest) GetPodUID() string {
	if x != nil {
		return x.PodUID
	}
	return ""
}

func (x *ConfigureNetworkRequest) GetResourceClaims() []*ResourceClaim {
	if x != nil {
		return x.ResourceClaims
	}
	return nil
}

type ResourceClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceClaim) Reset() {
	*x = ResourceClaim{}
	mi := &file_dra_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceClaim) ProtoMessage() {}

func (x *ResourceClaim) ProtoReflect() protoreflect.Message {
	mi := &file_dra_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceClaim.ProtoReflect.Descriptor instead.
func (*ResourceClaim) Descriptor() ([]byte, []int) {
	return file_dra_proto_rawDescGZIP(), []int{6}
}

func (x *ResourceClaim) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceClaim) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type ConfigureNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Interfaces    []*ConfiguredInterface `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureNetworkResponse) Reset() {
	*x = ConfigureNetworkResponse{}
	mi := &file_dra_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureNetworkResponse) ProtoMessage() {}

func (x *ConfigureNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dra_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureNetworkResponse.ProtoReflect.Descriptor instead.
func (*ConfigureNetworkResponse) Descriptor() ([]byte, []int) {
	return file_dra_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigureNetworkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureNetworkResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ConfigureNetworkResponse) GetInterfaces() []*ConfiguredInterface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type ConfiguredInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NicName       string                 `protobuf:"bytes,1,opt,name=nicName,proto3" json:"nicName,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	Gateway       string                 `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfiguredInterface) Reset() {
	*x = ConfiguredInterface{}
	mi := &file_dra_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfiguredInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfiguredInterface) ProtoMessage() {}

func (x *ConfiguredInterface) ProtoReflect() protoreflect.Message {
	mi := &file_dra_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfiguredInterface.ProtoReflect.Descriptor instead.
func (*ConfiguredInterface) Descriptor() ([]byte, []int) {
	return file_dra_proto_rawDescGZIP(), []int{8}
}

func (x *ConfiguredInterface) GetNicName() string {
	if x != nil {
		return x.NicName
	}
	return ""
}

func (x *ConfiguredInterface) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *ConfiguredInterface) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

var File_dra_proto protoreflect.FileDescriptor

const file_dra_proto_rawDesc = "" +
	"\n" +
	"\tdra.proto\x12\x03dra\"\x96\x01\n" +
	"\x17PrepareResourcesRequest\x12@\n" +
	"\x06claims\x18\x01 \x03(\v2(.dra.PrepareResourcesRequest.ClaimsEntryR\x06claims\x1a9\n" +
	"\vClaimsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdb\x01\n" +
	"\x18PrepareResourcesResponse\x12b\n" +
	"\x11preparedResources\x18\x01 \x03(\v24.dra.PrepareResourcesResponse.PreparedResourcesEntryR\x11preparedResources\x1a[\n" +
	"\x16PreparedResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.dra.PreparedResourceR\x05value:\x028\x01\"2\n" +
	"\x10PreparedResource\x12\x1e\n" +
	"\n" +
	"cdiDevices\x18\x01 \x03(\tR\n" +
	"cdiDevices\"9\n" +
	"\x19UnprepareResourcesRequest\x12\x1c\n" +
	"\tclaimUIDs\x18\x01 \x03(\tR\tclaimUIDs\"\x1c\n" +
	"\x1aUnprepareResourcesResponse\"\xf5\x01\n" +
	"\x17ConfigureNetworkRequest\x12\"\n" +
	"\fpodNamespace\x18\x01 \x01(\tR\fpodNamespace\x12\x18\n" +
	"\apodName\x18\x02 \x01(\tR\apodName\x12$\n" +
	"\rcontainerName\x18\x03 \x01(\tR\rcontainerName\x12\"\n" +
	"\fcontainerPid\x18\x04 \x01(\x05R\fcontainerPid\x12\x16\n" +
	"\x06podUID\x18\x05 \x01(\tR\x06podUID\x12:\n" +
	"\x0eresourceClaims\x18\x06 \x03(\v2\x12.dra.ResourceClaimR\x0eresourceClaims\"5\n" +
	"\rResourceClaim\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\"\x92\x01\n" +
	"\x18ConfigureNetworkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\"\n" +
	"\ferrorMessage\x18\x02 \x01(\tR\ferrorMessage\x128\n" +
	"\n" +
	"interfaces\x18\x03 \x03(\v2\x18.dra.ConfiguredInterfaceR\n" +
	"interfaces\"g\n" +
	"\x13ConfiguredInterface\x12\x18\n" +
	"\anicName\x18\x01 \x01(\tR\anicName\x12\x1c\n" +
	"\tipAddress\x18\x02 \x01(\tR\tipAddress\x12\x18\n" +
	"\agateway\x18\x03 \x01(\tR\agateway2\xff\x01\n" +
	"\x04Node\x12O\n" +
	"\x10PrepareResources\x12\x1c.dra.PrepareResourcesRequest\x1a\x1d.dra.PrepareResourcesResponse\x12U\n" +
	"\x12UnprepareResources\x12\x1e.dra.UnprepareResourcesRequest\x1a\x1f.dra.UnprepareResourcesResponse\x12O\n" +
	"\x10ConfigureNetwork\x12\x1c.dra.ConfigureNetworkRequest\x1a\x1d.dra.ConfigureNetworkResponseB\fZ\n" +
	"draProtos/b\x06proto3"

var (
	file_dra_proto_rawDescOnce sync.Once
	file_dra_proto_rawDescData []byte
)

func file_dra_proto_rawDescGZIP() []byte {
	file_dra_proto_rawDescOnce.Do(func() {
		file_dra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dra_proto_rawDesc), len(file_dra_proto_rawDesc)))
	})
	return file_dra_proto_rawDescData
}

var file_dra_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_dra_proto_goTypes = []any{
	(*PrepareResourcesRequest)(nil),    // 0: dra.PrepareResourcesRequest
	(*PrepareResourcesResponse)(nil),   // 1: dra.PrepareResourcesResponse
	(*PreparedResource)(nil),           // 2: dra.PreparedResource
	(*UnprepareResourcesRequest)(nil),  // 3: dra.UnprepareResourcesRequest
	(*UnprepareResourcesResponse)(nil), // 4: dra.UnprepareResourcesResponse
	(*ConfigureNetworkRequest)(nil),    // 5: dra.ConfigureNetworkRequest
	(*ResourceClaim)(nil),              // 6: dra.ResourceClaim
	(*ConfigureNetworkResponse)(nil),   // 7: dra.ConfigureNetworkResponse
	(*ConfiguredInterface)(nil),        // 8: dra.ConfiguredInterface
	nil,                                // 9: dra.PrepareResourcesRequest.ClaimsEntry
	nil,                                // 10: dra.PrepareResourcesResponse.PreparedResourcesEntry
}
var file_dra_proto_depIdxs = []int32{
	9,  // 0: dra.PrepareResourcesRequest.claims:type_name -> dra.PrepareResourcesRequest.ClaimsEntry
	10, // 1: dra.PrepareResourcesResponse.preparedResources:type_name -> dra.PrepareResourcesResponse.PreparedResourcesEntry
	6,  // 2: dra.ConfigureNetworkRequest.resourceClaims:type_name -> dra.ResourceClaim
	8,  // 3: dra.ConfigureNetworkResponse.interfaces:type_name -> dra.ConfiguredInterface
	2,  // 4: dra.PrepareResourcesResponse.PreparedResourcesEntry.value:type_name -> dra.PreparedResource
	0,  // 5: dra.Node.PrepareResources:input_type -> dra.PrepareResourcesRequest
	3,  // 6: dra.Node.UnprepareResources:input_type -> dra.UnprepareResourcesRequest
	5,  // 7: dra.Node.ConfigureNetwork:input_type -> dra.ConfigureNetworkRequest
	1,  // 8: dra.Node.PrepareResources:output_type -> dra.PrepareResourcesResponse
	4,  // 9: dra.Node.UnprepareResources:output_type -> dra.UnprepareResourcesResponse
	7,  // 10: dra.Node.ConfigureNetwork:output_type -> dra.ConfigureNetworkResponse
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_dra_proto_init() }
func file_dra_proto_init() {
	if File_dra_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dra_proto_rawDesc), len(file_dra_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dra_proto_goTypes,
		DependencyIndexes: file_dra_proto_depIdxs,
		MessageInfos:      file_dra_proto_msgTypes,
	}.Build()
	File_dra_proto = out.File
	file_dra_proto_goTypes = nil
	file_dra_proto_depIdxs = nil
}
